# Generated by Django 3.0.6 on 2020-05-26 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{12}$')]),
        ),
    ]
