# Generated by Django 2.1.7 on 2020-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200528_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezones',
            name='country_portion',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timezones',
            name='lat_long',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
