# Generated by Django 3.0.6 on 2020-06-11 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200609_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{12}$')]),
        ),
    ]
